name: openrefine
title: OpenRefine
base: core24
version: "3.9.5"
summary: A free, open source, powerful tool for working with messy data
description: |
  OpenRefine is a powerful tool for working with messy data:
  cleaning it; transforming it from one format into another; and extending it with web services and external data.
  OpenRefine always keeps your data private on your own computer until you want to share or collaborate. 
  Your private data never leaves your computer unless you want it to. 
  (It works by running a small server on your computer and you use your web browser to interact with it)
website: https://openrefine.org/
donation: https://openrefine.org/donate
issues: https://github.com/OpenRefine/OpenRefine/issues
source-code: https://github.com/OpenRefine/OpenRefine
license: BSD-3-Clause

grade: stable
confinement: strict
compression: lzo
icon: snap/gui/openrefine.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

parts:
  openrefine:
    plugin: dump
    source-type: tar
    source: https://github.com/OpenRefine/OpenRefine/releases/download/$SNAPCRAFT_PROJECT_VERSION/openrefine-linux-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    #   build-packages:
    #     - ca-certificates-java
    stage-packages:
      - curl
      - openjdk-21-jre-headless
      - procps
#    prime:
#      - -usr/lib/jvm/java-*/lib/security/blacklisted.certs

apps:
  openrefine:
    command: ./refine
    environment:
      # Ensure OpenRefine writes to snap's allowed user area
      HOME: ${SNAP_USER_COMMON}
      XDG_DATA_HOME: ${SNAP_USER_COMMON}/.local/share
      XDG_CONFIG_HOME: ${SNAP_USER_COMMON}/.config
      # Java settings and PATH
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
      JAVA_TOOL_OPTIONS: -Duser.home="${SNAP_USER_COMMON}" -Djava.awt.headless=true
      _JAVA_OPTIONS: -Duser.home="${SNAP_USER_COMMON}" -Djava.awt.headless=true
    plugs:
      - network
      - network-bind
      - x11
      - desktop
